Models/ErrorViewModel.cs
using System;

namespace sistema_reporte_ciudadano.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Incident.cs
using System.ComponentModel.DataAnnotations.Schema;
namespace sistema_reporte_ciudadano.Models
{
    public class  Incident
    {
        public int Id{ get; set;}
        public int IdZone{get; set;}
        public string Date{get; set;}
        public string Msg{get; set;}
        public string Media{get; set;}
        public int Votes{get; set;}

        [ForeignKey("User")]
        public int IdUser{get; set;}
        public User User{get; set;}
    }
}

Models/User.cs
using System.Collections.Generic;

namespace sistema_reporte_ciudadano.Models
{
    public class User
    {
        public int Id{ get; set;}
        public int IdZone{get; set;}
        public string Name{get; set;}
        public string Photo{get; set;}
        public string Email{get; set;}
        public string Password{get; set;}
        public List<Incident> Incidents {get; set;}
    }
}

Models/citizenReportContext.cs
using Microsoft.EntityFrameworkCore;
namespace sistema_reporte_ciudadano.Models
{
    public class citizenReportContext: DbContext
    {
        public citizenReportContext(DbContextOptions<citizenReportContext> options): base(options)
        {
        }

        public DbSet<User> Users{get; set;}
        public DbSet<Incident> Incidents{get; set;}
    }
}

Controllers/CitizenReportController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using sistema_reporte_ciudadano.Models;

namespace sistema_reporte_ciudadano.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class citizenReportController : ControllerBase
    {
        [HttpGet]
        public ActionResult<IEnumerable<User>> GetData()
        {
            User[] users = new User[]{
                new User{Id=1, IdZone=1, Name="Pedro", Photo="img/perro", Email="perro@gmail.com", Password="HDSJKAD"},
                new User{Id=2, IdZone=2, Name="Pedro", Photo="img/perro", Email="perro@gmail.com", Password="HDSJKAD"}
            };
            return users;
        }
    }
}

Controllers/HelloController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using sistema_reporte_ciudadano.Models;

namespace sistema_reporte_ciudadano.Controllers
{
    public class HelloController : Controller
    {
      public IActionResult HelloWorld() 
      {
        return View();
      }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using sistema_reporte_ciudadano.Models;

namespace sistema_reporte_ciudadano.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult HelloWorld()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Hello/HelloWorld.cshtml
@{
    ViewData["Title"] = "Esto es un demo";
}

<h1>Hola Mundo desde una nueva plantilla</h1>
<h2>Cambio</h2>
<h3>Cambio 2</h3>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - sistema_reporte_ciudadano</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">sistema_reporte_ciudadano</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hello" asp-action="HelloWorld">Hola Mundo</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - sistema_reporte_ciudadano - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>